# Generated by Django 3.0.4 on 2020-03-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-text'], 'verbose_name': 'Список дел для карточек', 'verbose_name_plural': 'Список дел для карточек'},
        ),
        migrations.AlterField(
            model_name='card',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='card',
            name='created',
            field=models.DateField(auto_now=True, verbose_name='Создано'),
        ),
    ]
